# DATA 
path: "/srv/local1/estengel/gr_data/"
batch_size: 32
max_seq_length: 40
resolution: 64
split_type: "random"
task_type: "rows" 
augment_by_flipping: False
augment_language: False 

# LANGUAGE EMBEDDER
embedder: random
embedding_dim: 15

# TRANSFORMER
patch_size: 4
n_shared_layers: 2
n_split_layers: 2
n_classes: 2
n_heads: 2
hidden_dim: 64
ff_dim: 128
dropout: 0.00
embed_dropout: 0.00
output_type: "per-patch" 
pos_encoding_type: fixed-2d-separate

# MISC
cuda: 0
learn_rate: 0.00
warmup: 400
checkpoint_dir: "" #"models/language_pretrain"
num_epochs: 201
generate_after_n: 199
score_type: "acc"
